### ISSUE TITLE
segfault when using -tfidfWeights

### ISSUE THREAD

**Issue by sld** [mwydmuch/extremeText#3]
Hi! Thanks for the lib.

I got `[1]    25799 segmentation fault` when I am using -tfidfWeights flag.

Ubuntu 18.04: `Linux 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`⚡ ⇒ extremeText/extremetext supervised -input data/tfidfextreme.txt -output model2 -epoch 100 -wordNgrams 4 -tfidfWeights -lr 1`

```
Training ...
  Model: sup, loss: softmax
  Features: TF-IDF weights, weightsThr: 0, buckets: 2000000
  Update: SGD, lr: 1, L2: 0, dims: 100, epochs: 100, neg: 0
Reading input file ...
Read 0M words
Number of documents: 4
Number of words: 4
Number of labels: 3
  Input: 2000004 x 100 (762M)
Setting up loss layer ...
  Output: 3 x 100 (0M)
Starting 4 threads ...
[1]    25799 segmentation fault (core dumped)  extremeText/extremetext supervised -input data/tfidfextreme.txt -output model
```

**Comment by mwydmuch** [comment]
Hi @sld, thank you for reporting the bug, I've fixed it. 
One additional remark `-wordNgrams` isn't supported for `-tfidfWeights` right now (it will be ignored). I plan to add support for it soon.
